"""Build the app and site icons from the brand images in ``assets/``.

Sources (kept at full size, edited by hand):
    assets/icon.png   round icon on a white square
    assets/logo.png   full logo with the wordmark, transparent background

Outputs, regenerated by ``make icons``:
    orbiter/assets/  icon.png, favicon.ico, icon-192.png, apple-touch-icon.png
    site/assets/     the same icons plus logo.png
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SOURCE_ICON = ROOT / "assets" / "icon.png"
SOURCE_LOGO = ROOT / "assets" / "logo.png"
APP_ASSETS = ROOT / "orbiter" / "assets"
SITE_ASSETS = ROOT / "site" / "assets"
# Background of the round icon, used where a platform needs an opaque square.
NAVY = (9, 21, 43, 255)
SUPERSAMPLE = 4
EDGE_INSET = 0.008


def round_icon() -> Image.Image:
    """Crop the dark disc out of its white square and make the rest transparent."""
    image = Image.open(SOURCE_ICON).convert("RGBA")
    dark = np.asarray(image.convert("L")) < 80
    rows, columns = np.nonzero(dark)
    left, right = columns.min(), columns.max()
    top, bottom = rows.min(), rows.max()
    size = max(right - left, bottom - top) + 1
    center_x, center_y = (left + right) / 2, (top + bottom) / 2
    box = (
        round(center_x - size / 2),
        round(center_y - size / 2),
        round(center_x + size / 2),
        round(center_y + size / 2),
    )
    disc = image.crop(box)

    # Antialiased circular mask, drawn large and scaled down. It is inset a
    # little so the white of the original square does not show as a halo.
    big = disc.width * SUPERSAMPLE
    inset = round(big * EDGE_INSET)
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).ellipse(
        (inset, inset, big - 1 - inset, big - 1 - inset), fill=255
    )
    disc.putalpha(mask.resize(disc.size, Image.Resampling.LANCZOS))
    return disc


def on_navy(icon: Image.Image, size: int) -> Image.Image:
    """Opaque square version for platforms that fill transparency (iOS)."""
    square = Image.new("RGBA", (size, size), NAVY)
    scaled = icon.resize((size, size), Image.Resampling.LANCZOS)
    square.alpha_composite(scaled)
    return square.convert("RGB")


def main() -> None:
    """Write every icon size for the app and the project page."""
    icon = round_icon()
    APP_ASSETS.mkdir(parents=True, exist_ok=True)
    icon.resize((256, 256), Image.Resampling.LANCZOS).save(APP_ASSETS / "icon.png")
    icon.save(
        APP_ASSETS / "favicon.ico", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)]
    )
    icon_192 = icon.resize((192, 192), Image.Resampling.LANCZOS)
    icon_192.save(APP_ASSETS / "icon-192.png")
    on_navy(icon, 180).save(APP_ASSETS / "apple-touch-icon.png")

    SITE_ASSETS.mkdir(parents=True, exist_ok=True)
    for name in ("icon.png", "favicon.ico", "icon-192.png", "apple-touch-icon.png"):
        shutil.copy(APP_ASSETS / name, SITE_ASSETS / name)
    logo = Image.open(SOURCE_LOGO).convert("RGBA")
    logo = logo.crop(logo.getbbox())
    logo.thumbnail((720, 720), Image.Resampling.LANCZOS)
    logo.save(SITE_ASSETS / "logo.png", optimize=True)
    app, site = APP_ASSETS.relative_to(ROOT), SITE_ASSETS.relative_to(ROOT)
    print(f"Icons written to {app} and {site}")


if __name__ == "__main__":
    main()
